using Inferior.Core.DataBus;
using Inferior.Core.Simulation;

namespace Inferior.Gameplay.Components;

/// <summary>
/// Common base for every installed ship component — power-bus consumers, sensors,
/// shields, drives, gyro, and battery-backed components alike.
///
/// Battery-backed components (FlyabilityMonitor, life support, cockpit) derive from this
/// but set PowerConsumption = 0 and are not registered with PowerPriorityManager.
/// </summary>
public abstract class ShipComponent
{
    // ── Identity ──────────────────────────────────────────────────────────────
    /// <summary>Used in bus messages and diagnostics. e.g. "MainEngine", "TopShield".</summary>
    public string Name { get; init; } = string.Empty;

    /// <summary>Whether the engineering panel may request this device on or off.</summary>
    public virtual bool CanSetPower => true;

    public string PowerCommandTopic => $"{Name}.Power.Set";

    /// <summary>Live values selected for the engineering topology view.</summary>
    public virtual IReadOnlyList<ShipSystemMetricBinding> EngineeringMetrics => [];

    // ── Lifecycle ──────────────────────────────────────────────────────────────
    public ComponentStatus Status { get; protected set; } = ComponentStatus.PowerOff;

    /// <summary>
    /// The component's power switch. Setting true requests startup; false shuts it down.
    /// A component can be switched on before bus power is available — it will wait in
    /// PowerOn status until NotifyPowerAvailable() is called by the power system.
    /// </summary>
    private bool _powerOn;
    public bool PowerOn
    {
        get => _powerOn;
        set
        {
            if (_powerOn == value) return;
            _powerOn = value;

            if (_powerOn)
            {
                // Can only go to PowerOn if powered off 
                if (Status == ComponentStatus.PowerOff)
                {
                    Status = ComponentStatus.PowerOn;
                    OnPowerOn();
                }
            }
            else
            {
                _startupElapsed = 0.0;
                Status = ComponentStatus.PowerOff;
                OnPowerOff();
            }
        }
    }

    /// <summary>
    /// Seconds from power-on until the component transitions to Started.
    /// 0.0 = instant startup — no sequence messages, goes directly to Started.
    /// Non-zero produces the full cold-start sequence with status messages.
    /// Set to double.PositiveInfinity for self-managed startup via CompleteInitialization().
    /// </summary>
    public double StartupTimer { get; init; } = 0.0;

    private double _startupElapsed;

    // ── Power ──────────────────────────────────────────────────────────────────
    /// <summary>
    /// Local energy buffer in joules. Absorbs brief supply interruptions without
    /// the component noticing. Size generously for ArtificialGravity; minimally for a sensor.
    /// </summary>
    public double InputCapacitorMaxJ    { get; init; } = 0.0;
    public double InputCapacitorChargeJ { get; protected set; }

    /// <summary>
    /// Nominal peak draw in watts. Used by FlyabilityMonitor overspec checks.
    /// Reflects maximum demand, not instantaneous — actual draw varies with load.
    /// </summary>
    public double PowerConsumption { get; init; }  // watts

    // ── Health ────────────────────────────────────────────────────────────────
    public double Efficiency          { get; protected set; } = 1.0;  // 0.0–1.0
    public double Damage              { get; protected set; } = 0.0;  // 0.0 = pristine, 1.0 = destroyed
    /// <summary>Net effective efficiency after damage. Used to compute heat generated by imperfect conversion.</summary>
    public double EffectiveEfficiency => Efficiency * (1.0 - Damage);

    /// <summary>
    /// Accumulate damage from excess heat. Called by TickDamage when ThermalNode.IsFailure.
    /// excessHeatJ: joules above MaxHeatJ — used to scale the accumulation rate.
    /// Virtual — subclasses may override to tune the rate per component type.
    /// </summary>
    public virtual void AccumulateDamage(double excessHeatJ, double dt)
        => Damage = Math.Min(1.0, Damage + excessHeatJ * dt * 0.0001);  // rate TBD

    // ── Heat ──────────────────────────────────────────────────────────────────
    /// <summary>
    /// Null for battery-backed components that generate no heat.
    /// Heated components construct this in their own constructor, passing the appropriate
    /// HeatCapacity (J/K) and MaxHeatJ (joules). Those values live on the node.
    /// </summary>
    public ThermalNode? ThermalNode { get; protected init; }

    // ── Sensors ───────────────────────────────────────────────────────────────
    public IReadOnlyList<ComponentSensor> Sensors => _sensors;
    protected readonly List<ComponentSensor> _sensors = new();

    /// <summary>Additional simulation command topics accepted directly by this device.</summary>
    protected virtual IReadOnlyList<string> DeviceCommandTopics => [];

    private bool _deviceInfoPublished;
    private bool _deviceStatePublished;
    private ComponentStatus _publishedStatus;
    private double _publishedDamage;
    private double _publishedEfficiency;
    private readonly List<(string Prefix, Action<ComponentCommand> Handler)> _commandHandlers = [];
    private readonly List<IDisposable> _commandSubscriptions = [];
    private bool _busActive;

    // ── Events ────────────────────────────────────────────────────────────────
    /// <summary>
    /// Fired once when the component transitions to Started.
    /// Subscribe here for physics responses — e.g. a shield-start roll impulse.
    /// </summary>
    public event Action? Started;

    // ── Power system interface ────────────────────────────────────────────────
    /// <summary>
    /// Called by the power system when bus power becomes available.
    /// Ignored if the component is switched off or already running.
    /// Components with StartupTimer == 0 go directly to Started (no sequence messages).
    /// Components with StartupTimer > 0 begin the cold-start sequence via Tick().
    /// </summary>
    public void NotifyPowerAvailable()
    {
        if (!_powerOn) return;
        if (Status is ComponentStatus.Initializing or ComponentStatus.Running) return;

        if (StartupTimer <= 0.0)
        {
            Status = ComponentStatus.Running;
            OnInitializationComplete();
            Started?.Invoke();
        }
        else
        {
            Status = ComponentStatus.PowerOn;
        }
    }

    // ── Tick ──────────────────────────────────────────────────────────────────
    /// <summary>
    /// Drives the startup state machine, then delegates to OnTick once Started.
    /// Not virtual — override OnTick instead.
    /// </summary>
    public void Tick(double dt)
    {
        PublishDeviceInfoOnce();
        TickStartupSequence(dt);

        if (Status == ComponentStatus.Running)
        {
            OnTick(dt);
            if (ThermalNode?.IsFailure == true)
                AccumulateDamage(ThermalNode.ExcessHeatJ, dt);
        }
        else if (Status == ComponentStatus.PowerOff)
            OnPowerOffTick(dt);

        PublishDeviceStateIfChanged();
    }

    /// <summary>Attach this installed component to the current command bus.</summary>
    public void ActivateBus()
    {
        if (_busActive)
            return;

        _busActive = true;
        if (CanSetPower && !string.IsNullOrWhiteSpace(Name))
        {
            _commandSubscriptions.Add(CommandBus.Subscribe(
                PowerCommandTopic,
                command =>
                {
                    if (string.Equals(command.Topic, PowerCommandTopic, StringComparison.Ordinal))
                        PowerOn = command.Value >= 0.5;
                }));
        }
        foreach (ComponentSensor sensor in _sensors)
            sensor.ActivateBus();
        foreach (var (prefix, handler) in _commandHandlers)
            _commandSubscriptions.Add(CommandBus.Subscribe(prefix, handler));
    }

    /// <summary>Detach this component when its ship is no longer the active bus owner.</summary>
    public void DeactivateBus()
    {
        if (!_busActive)
            return;

        _busActive = false;
        foreach (ComponentSensor sensor in _sensors)
            sensor.DeactivateBus();
        foreach (IDisposable subscription in _commandSubscriptions)
            subscription.Dispose();
        _commandSubscriptions.Clear();
    }

    protected virtual void OnTick(double dt) { }

    /// <summary>
    /// Called every tick while Status == PowerOff. Override for post-shutdown behaviour
    /// such as capacitor drain or thermal dissipation. Default no-ops.
    /// </summary>
    protected virtual void OnPowerOffTick(double dt) { }

    // ── Lifecycle hooks ───────────────────────────────────────────────────────
    /// <summary>Called once when the startup timer begins running (StartupTimer > 0 only).</summary>
    protected virtual void OnInitializationStarted()
        => DataBus.SystemMessages.Publish(Topics.System.All, new($"{Name}: initializing"));

    /// <summary>
    /// Called every tick while Status == Initializing. Override to run warmup physics
    /// and post progress messages. Call CompleteInitialization() here when ready for
    /// self-managed components (StartupTimer = double.PositiveInfinity).
    /// </summary>
    protected virtual void OnInitializingTick(double dt) { }

    /// <summary>
    /// Called once when the component reaches Started. Publishes sensor ranges and
    /// the online message. Override to customise — call PublishTelemetryInfo() yourself
    /// in place of base.OnInitializationComplete().
    /// </summary>
    protected virtual void OnInitializationComplete()
    {
        PublishTelemetryInfo();
        DataBus.SystemMessages.Publish(Topics.System.All, new($"{Name}: online"));
    }

    /// <summary>
    /// Called once when the component is powered off from any running state.
    /// Override to add component-specific shutdown behaviour (drain capacitor, etc.).
    /// Base publishes the offline message.
    /// </summary>
    protected virtual void OnPowerOff()
        => DataBus.SystemMessages.Publish(Topics.System.All, new($"{Name}: offline"));

    /// <summary>
    /// Called once when the component is powered on.
    /// Override to add component-specific startup behaviour (charge capacitor, etc.).
    /// Base publishes the online message.
    /// </summary>
    protected virtual void OnPowerOn()
        => DataBus.SystemMessages.Publish(Topics.System.All, new($"{Name}: powering up"));

    /// <summary>
    /// Transitions directly to Started from Initializing. For components that manage
    /// their own completion condition (e.g. a shield waiting for full capacitor charge)
    /// rather than relying on StartupTimer. Safe to call from OnInitializingTick.
    /// </summary>
    protected void CompleteInitialization()
    {
        if (Status != ComponentStatus.Initializing) return;
        Status = ComponentStatus.Running;
        OnInitializationComplete();
        Started?.Invoke();
    }

    // ── Protected helpers ─────────────────────────────────────────────────────
    protected void PublishTelemetryInfo()
    {
        foreach (var s in _sensors)
            s.PublishInfo();
    }

    protected void TickSensors()
    {
        foreach (var s in _sensors)
            s.Tick();
    }

    protected void RegisterCommand(string prefix, Action<ComponentCommand> handler)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(prefix);
        ArgumentNullException.ThrowIfNull(handler);
        _commandHandlers.Add((prefix, handler));
        if (_busActive)
            _commandSubscriptions.Add(CommandBus.Subscribe(prefix, handler));
    }

    private void PublishDeviceInfoOnce()
    {
        if (_deviceInfoPublished || string.IsNullOrWhiteSpace(Name))
            return;

        _deviceInfoPublished = true;
        string[] publishedTopics = _sensors.Select(sensor => sensor.Topic).ToArray();
        var commandTopics = _sensors
            .Select(sensor => sensor.QueryCommandTopic)
            .Concat(DeviceCommandTopics)
            .ToList();
        if (CanSetPower)
            commandTopics.Add(PowerCommandTopic);

        DataBus.DeviceInfo.Publish(Name, new DeviceInfo
        {
            DeviceId = Name,
            PublishedTopics = [.. publishedTopics],
            CommandTopics = [.. commandTopics],
            Power = new PowerProfile(
                IdleWatts: 0.0,
                ActiveWatts: PowerConsumption,
                ActivationDurationSeconds:
                    double.IsFinite(StartupTimer) ? Math.Max(0.0, StartupTimer) : 0.0),
        });
    }

    private void PublishDeviceStateIfChanged()
    {
        if (string.IsNullOrWhiteSpace(Name) ||
            (_deviceStatePublished &&
             _publishedStatus == Status &&
             _publishedDamage.Equals(Damage) &&
             _publishedEfficiency.Equals(Efficiency)))
        {
            return;
        }

        _deviceStatePublished = true;
        _publishedStatus = Status;
        _publishedDamage = Damage;
        _publishedEfficiency = Efficiency;

        DataBus.DeviceState.Publish(Name, new DeviceState(
            Name,
            Status switch
            {
                ComponentStatus.PowerOff => DeviceOperationalStatus.PowerOff,
                ComponentStatus.PowerOn => DeviceOperationalStatus.PowerOn,
                ComponentStatus.Initializing => DeviceOperationalStatus.Initializing,
                ComponentStatus.Running => DeviceOperationalStatus.Running,
                _ => DeviceOperationalStatus.Unavailable,
            },
            Damage,
            Efficiency,
            GameClock.SimTime));
    }

    // ── Private ───────────────────────────────────────────────────────────────
    private void TickStartupSequence(double dt)
    {
        switch (Status)
        {
            case ComponentStatus.PowerOn:
                Status = ComponentStatus.Initializing;
                OnInitializationStarted();
                break;

            case ComponentStatus.Initializing:
                _startupElapsed += dt;
                OnInitializingTick(dt);
                // Guard: OnInitializingTick may have called CompleteInitialization() already
                if (Status == ComponentStatus.Initializing && _startupElapsed >= StartupTimer)
                {
                    Status = ComponentStatus.Running;
                    OnInitializationComplete();
                    Started?.Invoke();
                }
                break;
        }
    }
}
