using Inferior.Core.DataBus;

namespace Inferior.Gameplay.Components.Power;

/// <summary>
/// Primary power source. Generates power from fuel at a throttleable output level.
/// Has an output capacitor that buffers generated power before distribution.
///
/// Heat generated = output × (1 − Efficiency). Cooling is applied externally by
/// the coolant system — there is no passive dissipation.
///
/// Sensors published every tick:
///   {Name}.Output       — current power output (watts; ScaleFactor=1e-6 → display in MW)
///   {Name}.Capacitor    — output capacitor fill level (0–1)
///   {Name}.Temperature  — thermal node temperature (Kelvin)
///   {Name}.Efficiency   — current efficiency (0–1)
///   {Name}.Damage       — damage level (0–1)
///
/// Commands accepted:
///   {Name}.Throttle.Set  value 0–1  — set output throttle
/// </summary>
public sealed class PowerReactor : ShipComponent
{
    public override IReadOnlyList<ShipSystemMetricBinding> EngineeringMetrics =>
    [
        new(ShipSystemMetricRole.PowerOutput, $"{Name}.Output"),
        new(ShipSystemMetricRole.PowerFlow, $"{Name}.Drawn"),
        new(ShipSystemMetricRole.CapacitorFill, $"{Name}.Capacitor"),
        new(ShipSystemMetricRole.HeatGeneration, $"{Name}.{Topics.Engineering.HeatGeneration}"),
        new(ShipSystemMetricRole.ThermalLoad, $"{Name}.{Topics.Engineering.ThermalLoad}"),
        new(ShipSystemMetricRole.Temperature, $"{Name}.Temperature"),
    ];

    protected override IReadOnlyList<string> DeviceCommandTopics => [$"{Name}.Throttle.Set"];

    public double MaxPower      { get; }
    public double Throttle      { get; private set; } = 1.0;
    public double CurrentOutput { get; private set; }
    /// <summary>Watts drawn from the output capacitor last tick (total across all connected buses).</summary>
    public double DrawnWatts    { get; private set; }

    /// <summary>Output capacitor — connect to a PowerBus via bus.ConnectSource(reactor.OutputCapacitor).</summary>
    public PowerCapacitor OutputCapacitor { get; }

    public PowerReactor(string name, double maxPower, double outputCapacitorJ,
                        double efficiency   = 0.85,
                        double heatCapacity = 80_000.0,    // J/K
                        double maxHeatJ     = 120_000_000.0) // joules (equiv. ~1500 K × 80 kJ/K)
    {
        Name            = name;
        MaxPower        = maxPower;
        Efficiency      = efficiency;
        OutputCapacitor = new PowerCapacitor(outputCapacitorJ);
        ThermalNode     = new ThermalNode(heatCapacity, maxHeatJ);

        RegisterSensors();
        RegisterCommands();
    }

    protected override void OnTick(double dt)
    {
        // Snapshot joules drawn from the output capacitor since last tick (by all connected buses),
        // then reset accumulator before charging so only new draws count next tick.
        DrawnWatts = dt > 0.0 ? OutputCapacitor.SnapshotAndResetDrawn() / dt : 0.0;

        double target   = MaxPower * Throttle;
        CurrentOutput   = target * Efficiency;

        OutputCapacitor.Charge(CurrentOutput, dt);

        // Heat generated by inefficiency — cooling applied externally by coolant system.
        // Higher throttle generates disproportionately more heat (compressor heat curve).
        if (ThermalNode != null)
        {
            double curve = Throttle <= 0.60 ? 1.0
                         : Throttle <= 0.80 ? 1.5
                         : Throttle <= 0.90 ? 2.5
                         :                    4.0;
            double heatW = CurrentOutput * (1.0 - Efficiency) * curve;
            ThermalNode.Update(heatW, dt);
        }

        TickSensors();
    }

    protected override void OnPowerOffTick(double dt)
    {
        CurrentOutput = 0.0;
        double drawnJ = OutputCapacitor.SnapshotAndResetDrawn();
        DrawnWatts = dt > 0.0 ? drawnJ / dt : 0.0;
        ThermalNode?.Update(0.0, dt);
        TickSensors();
    }

    protected override void OnInitializationComplete()
    {
        PublishTelemetryInfo();
        DataBus.SystemMessages.Publish(Topics.System.All,
            new($"{Name}: online — {MaxPower / 1e6:F0} MW reactor, " +
                $"{OutputCapacitor.MaxJ / 1e6:F1} MJ capacitor"));
    }

    // ── Private ───────────────────────────────────────────────────────────────

    private void RegisterSensors()
    {
        // Safe temperature = warning threshold (70% of max); total = 100%
        double maxTempK  = ThermalNode != null ? ThermalNode.MaxHeatJ / ThermalNode.HeatCapacity : 1.0;
        double safeTempK = maxTempK * 0.7;

        _sensors.Add(new ComponentSensor(
            $"{Name}.Output",
            () => CurrentOutput,                           // watts — ScaleFactor=1e-6 for MW display
            safeRange:  new RangeValue(0, MaxPower * 0.85),
            totalRange: new RangeValue(0, MaxPower),
            quantity: PhysicalQuantity.Power));

        _sensors.Add(new ComponentSensor(
            $"{Name}.Drawn",
            () => DrawnWatts,                              // watts — ScaleFactor=1e-6 for MW display
            safeRange:  new RangeValue(0, MaxPower * 0.85),
            totalRange: new RangeValue(0, MaxPower),
            quantity: PhysicalQuantity.Power));

        _sensors.Add(new ComponentSensor(
            $"{Name}.Capacitor",
            () => OutputCapacitor.FillFraction,
            safeRange:  new RangeValue(0.1, 1.0),
            totalRange: new RangeValue(0.0, 1.0),
            quantity: PhysicalQuantity.NormalizedRatio));

        _sensors.Add(new ComponentSensor(
            $"{Name}.Temperature",
            () => ThermalNode?.Temperature ?? 0.0,         // Kelvin
            safeRange:  new RangeValue(0, safeTempK),
            totalRange: new RangeValue(0, maxTempK),
            quantity: PhysicalQuantity.Temperature));

        double maxHeatW = MaxPower * Math.Max(0.0, 1.0 - Efficiency) * 4.0;
        _sensors.Add(new ComponentSensor(
            $"{Name}.{Topics.Engineering.HeatGeneration}",
            () => ThermalNode?.LastHeatInputW ?? 0.0,
            safeRange: new RangeValue(0, maxHeatW * 0.7),
            totalRange: new RangeValue(0, maxHeatW),
            quantity: PhysicalQuantity.Power));

        _sensors.Add(new ComponentSensor(
            $"{Name}.{Topics.Engineering.ThermalLoad}",
            () => ThermalNode?.NormalizedTemperature ?? 0.0,
            safeRange: new RangeValue(0, 0.7),
            totalRange: new RangeValue(0, 1.0),
            quantity: PhysicalQuantity.NormalizedRatio));

        _sensors.Add(new ComponentSensor(
            $"{Name}.Efficiency",
            () => Efficiency,
            safeRange:  new RangeValue(0.75, 1.0),
            totalRange: new RangeValue(0.0,  1.0),
            quantity: PhysicalQuantity.NormalizedRatio));

        _sensors.Add(new ComponentSensor(
            $"{Name}.Damage",
            () => Damage,
            safeRange:  new RangeValue(0.0, 0.2),
            totalRange: new RangeValue(0.0, 1.0),
            quantity: PhysicalQuantity.NormalizedRatio));
    }

    private void RegisterCommands()
    {
        RegisterCommand($"{Name}.Throttle.Set",
            cmd => Throttle = Math.Clamp(cmd.Value, 0.0, 1.0));
    }
}
